[build]
  base = "apps/web"
  command = "cd ../.. && npm ci && npm -w @holmeta/web run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_BUILD_DEBUG = "true"
  CI = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
